POST http://localhost:3005/employees/add
content-type: application/json

{
  "name": "Ben",
  "department": "operations",
  "subDepartment": "Other",
  "email": "ben@fakeMail.com",
  "phone": "431163122",
  "status": "active",
  "shift": {
    "start": "20:00",
    "length": 8
  }
}
# {
#     "name": "Emily",
#     "department": "cs",
#     "type": "Other",
#     "team": "test",
#     "email": "emily@paintyourlife.com",
#     "phone": "43555214",
#     "status": "active",
#     "shift": {
#       "start": "13:00",
#       "length": 8
#     }
# }
# {
#     "name": "Rick",
#     "department": "editing",
#     "type": "QC",
#     "email": "rick@paintyourlife.com",
#     "phone": "54322345",
#     "status": "active",
#     "shift": {
#       "start": "17:00",
#       "length": 8
#     }
# }